name: Bug report
description: Create a report to help us improve
labels: bug
assignees: iruzevic
body:
    - type: markdown
      attributes:
          value: |
              Hi there! We see that you like our project and you have found a bug. This means a lot to us because it helps us to improve it even more :)

    - type: textarea
      attributes:
          label: Describe your bug
          description: Please write a clear and concise description of what the bug is.
          placeholder: |
              Example. When I try to do this, I get this and it should be this...
      validations:
          required: true

    - type: textarea
      attributes:
          label: Steps to Reproduce
          description: Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant, that means a lot to us.
          placeholder: |
              1.
              2.
              3.
              4.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Expected behavior
          description: Please write a clear and concise description of what you expected to happen.
          placeholder: |
            Example. I should get this...
      validations:
          required: true

    - type: textarea
      attributes:
          label: Screenshots, screen recording, code snippet
          description: |
            If possible, please upload a screenshot or screen recording which demonstrates your bug.
      validations:
          required: false

    - type: textarea
      attributes:
          label: Environment info
          description: |
            Please include as many relevant details about the environment you are working on.
          placeholder: |
            - PHP version
            - Development environment (MAMP, XAMPP, VVV, Docker, Laravel Valet, none if on live server)
            - Server type (Apache, Nginx, IIS)
            - Operating System and version
            - Libs version
      validations:
          required: false

    - type: dropdown
      id: existing
      attributes:
          label: Please confirm that you have searched existing issues in this repo.
          description: You can do this by searching https://github.com/infinum/eightshift-libs/issues.
          multiple: false
          options:
            - 'Yes'
            - 'No'
      validations:
          required: true

    - type: dropdown
      id: docs
      attributes:
          label: Please confirm that you have searched in our documentation and couldn't find the answer.
          description: You can do this by searching https://eightshift.com/.
          multiple: false
          options:
            - 'Yes'
            - 'No'
      validations:
          required: true

    - type: dropdown
      id: plugin
      attributes:
          label: Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.
          multiple: false
          options:
            - 'Yes'
            - 'No'
      validations:
          required: true
