name: Feature request
description: Suggest an idea for this project
labels: feature request
assignees: iruzevic
body:
    - type: markdown
      attributes:
          value: |
              Hi there! We see that you like our project and you have some ideas. This means a lot to us because it helps us to improve it even more :)
    - type: textarea
      attributes:
          label: Describe your feature request
          description: Please write a clear and concise description of what the problem is.
          placeholder: |
              Example. I'm always frustrated when...
      validations:
          required: true

    - type: textarea
      attributes:
          label: Describe the solution you'd like
          description: Please write a clear and concise description of what you want to happen.
          placeholder: |
              Example. With this feature I will be able to...
      validations:
          required: true

    - type: textarea
      attributes:
          label: Screenshots, screen recording, code snippet
          description: |
              If possible, please upload a screenshot or screen recording which demonstrates your feature request.
      validations:
          required: false

    - type: textarea
      attributes:
          label: Environment info
          description: |
            Please include as many relevant details about the environment you are working on.
          placeholder: |
            - PHP version
            - Development environment (MAMP, XAMPP, VVV, Docker, Laravel Valet, none if on live server)
            - Server type (Apache, Nginx, IIS)
            - Operating System and version
            - Libs version
      validations:
          required: false

    - type: dropdown
      id: existing
      attributes:
          label: Please confirm that you have searched existing issues in this repo.
          description: You can do this by searching https://github.com/infinum/eightshift-libs/issues.
          multiple: false
          options:
            - 'Yes'
            - 'No'
      validations:
          required: true

    - type: dropdown
      id: docs
      attributes:
          label: Please confirm that you have searched in our documentation and couldn't find the answer.
          description: You can do this by searching https://eightshift.com/.
          multiple: false
          options:
            - 'Yes'
            - 'No'
      validations:
          required: true
