name: Continuous Integration

on:
    push:
        branches:
            - "develop"
            - "main"
        paths-ignore:
            - "**.md"
    pull_request:
        paths-ignore:
            - "**.md"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    composer:
        name: Composer checks
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - name: Composer checks
              uses: infinum/eightshift-deploy-actions-public/.github/actions/lint/composer@main
              with:
                  PROJECT_PATH: ""
                  WORDPRESS_GH_ACTIONS: ${{ secrets.WORDPRESS_GH_ACTIONS }}
